<a href="https://colab.research.google.com/github/saimaheswar/PYTHON1/blob/master/DAY_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
def test():
    print("Test() for funcyion")
    return
test()

Test() for funcyion


In [3]:
class Demo:
    def test(self):
        print("test() for the class and method")
        return
obj=Demo()
obj.test()

test() for the class and method


In [4]:
class Demo2:
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
    def add(self,p1,p2):
        return p1+p2
c1=Demo2(10,20)
print(c1.add(100,200))
    
        

300


In [5]:
class person(object):
    def __init__(self,name):
        self.name = name
    def getname(self):
        return self.name
    def isemployee(self):
        return False
    
#derived class
class employee(person):
    def isemployee(self):
        return True
emp = person("Anil")
print(emp.getname(),emp.isemployee())

emp1=employee("bharath")
print(emp1.getname(),emp1.isemployee())
        

Anil False
bharath True


In [6]:
import numpy as np
lst=[1,2,3,4,5]
array = np.array(lst)
print(array)

[1 2 3 4 5]


In [7]:
import numpy as np
lst=[1,2,3,4,5]
array = np.array(lst)
print(array.shape)
print(array.dtype)

(5,)
int64


In [9]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)


[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [0]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
print(np.hstack((a1,a2)))

[1 2 3 4 5 6]


In [10]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [11]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
print("first row: ",a1[0])
print("second row: ",a1[1])
print("slicing coloum :",a1[:,0])
print("slicing coloum :",a1[:,1])


[[1 2 3]
 [4 5 6]]
first row:  [1 2 3]
second row:  [4 5 6]


In [17]:

a1=np.random.normal(5,1,10)
print(a1)
print("Min value = ",np.min(a1))
print("Max value = ",np.max(a1))
print("Mean value = ",np.mean(a1))
print("median value = ",np.median(a1))

[3.88812236 5.91047181 7.20879491 5.62279144 6.17760508 5.10449881
 5.3063821  4.32944954 6.14983429 5.01401336]
Min value =  3.888122361507432
Max value =  7.208794910280666
Mean value =  5.47119637127823
median value =  5.464586770142627


In [18]:
c1=np.array([(1,2),(3,4)])
c2=np.array([(3,4),(1,2)])
np.dot(c1,c2)

array([[ 5,  8],
       [13, 20]])

In [19]:
import pandas as pd
dict = {"Name":["Anil","Akhil","Dinesh","Harsha","Ajay","Kranth"],
        "EmailID":["anil@gmail.com","akhil@gmail.com","dinesh@gmail.com",
                   "harsha@gmail.com","ajay@gmail.com","kranth@gmail.com"],
        "MobileNumber":[999,888,777,888,777,999],
        "Address":["Hyd","Hyd","Hyd","Hyd","Hyd","Hyd"]}
b=pd.DataFrame(dict)
print(b)

     Name           EmailID  MobileNumber Address
0    Anil    anil@gmail.com           999     Hyd
1   Akhil   akhil@gmail.com           888     Hyd
2  Dinesh  dinesh@gmail.com           777     Hyd
3  Harsha  harsha@gmail.com           888     Hyd
4    Ajay    ajay@gmail.com           777     Hyd
5  Kranth  kranth@gmail.com           999     Hyd
