In [2]:
class Demo:
    def test(self):
        print(f"tested")
    def check(self):
        print(f"checked")
obj = Demo()
obj.test()
obj.check()
        

tested
checked


In [3]:
import numpy as np
a= np.array([1,2,3,4])
b=np.array([4,5,6,7])
c = a+b
c= a*b
print(c)

[ 4 10 18 28]


In [4]:
class Car:
    def __init__(self,name,color):
        self.Name = name
        self.color= color
obj = Car()
print(f"i bought an {obj.Name} car. which is in {obj.color} color ")

TypeError: __init__() missing 2 required positional arguments: 'name' and 'color'

In [16]:
class Person:
    def __init__(self,name):
        self.name = name
    def getName(self):
        return self.name
    def isEmployee(self):
        return False
class Employee(Person):
    def isEmployee(self):
        return True
emp = Person("kaif")
print(emp.getName(),emp.isEmployee())
emp1 = Employee("kaif")
print(emp1.getName(),emp1.isEmployee())

kaif False
kaif True


# NUMPY

In [3]:
import numpy as np
lst = [[1,2,3,4],
      [5,6,7,8]]
array = np.array(lst)
print(lst)
print(array)
print(array[1][2])
print(lst[1][2])

[[1, 2, 3, 4], [5, 6, 7, 8]]
[[1 2 3 4]
 [5 6 7 8]]
7
7


In [4]:
lst = [1,2,3]
array = np.array(lst)
a2 = np.array([4,5,6])
print(np.vstack((array,a2)))

[[1 2 3]
 [4 5 6]]


In [5]:
arr = np.zeros((2,2),dtype = np.int64)
print(arr)

[[0 0]
 [0 0]]


In [6]:
arr = np.ones((3,4), dtype = np.int64)
print(arr)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [7]:
mat = np.matrix(np.ones((4,4),dtype= np.int64))
print(mat)
np.asarray(mat)[2][1]=5
print()
print(mat)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]

[[1 1 1 1]
 [1 1 1 1]
 [1 5 1 1]
 [1 1 1 1]]


In [12]:
np.arange(0,20,5)

array([ 0,  5, 10, 15])

In [47]:
a1 = np.random.normal(5,1,10)
print(a1)

[6.07893497 5.27098466 4.92332143 3.7725289  4.92976661 3.82065976
 4.36017647 4.26326395 4.42770437 4.27856558]


In [129]:
np.median(a1)

4.393940422455113

In [131]:
a = [1,2,3]
b = [4,5,6]
np.dot(a,b)

32

# Pandas
    it is used for data analysis

In [10]:
import pandas as pd
dict = {"name":["kaif ali khan","sadujdfsd","asfgjknkj"],
       "Email":["kaif@gmail.com","sadad@gmail.com","asd@gmail.com"],
       "phone":[3256482,54815184,1986111456]}
d = pd.DataFrame(dict)
print(d)

            name            Email       phone
0  kaif ali khan   kaif@gmail.com     3256482
1      sadujdfsd  sadad@gmail.com    54815184
2      asfgjknkj    asd@gmail.com  1986111456


In [31]:
import numpy as np
def numFrequency(sen):
    lst2 = np.zeros((1,10), dtype = np.int64)
    
    lst = list(sen)
    
    for i in range(len(lst)):
        if ord(lst[i])>=48 and ord(lst[i])<=57:
            k=ord(lst[i])-48
            lst2[0][k]=lst2[0][k]+1
    print(lst2)
numFrequency("213abc456def111")
            

[[0 4 1 1 1 1 1 0 0 0]]
